"use strict";
var dataLevels = {
    statusBad: 'Bad',
    statusMedium: 'Medium',
    statusGood: 'Good'
}
var AppData = {
    //list of Contracts
    listOfContracts: [
        {
            contractNumber: '54867972',
            contractMacAddress: '58-90-77-22-75-5C',
            contractHgwInfo: {
                wifiEnabled: true,
                hgwStandard: '802.11b',
                ipAddress: '192.168.1.1',
                ssid: 'ibis-wifi',
                channel: 6,
                security: 'WPA/WPA2-PSK',
                band: '2,4 GHz',
                hiddenSsid: false,
                bandwith: '22 MHZ',
                upTime: '(34572) 2 days, 19:04:10',
                equipment: 'ACB',
                description: 'modem',
                cmtsId: 'BG-C-1-IBIS',
                firmware: '2.2.1004.78'
            }
        },
        {
            contractNumber: '31495080',
            contractMacAddress: '5A-3D-30-13-8F-15',
            contractHgwInfo: {
                wifiEnabled: false,
                hgwStandard: '802.11b',
                ipAddress: '192.168.1.1',
                ssid: 'golf-net',
                channel: 12,
                security: 'WPA/WPA2-PSK',
                band: '2,4 GHz',
                hiddenSsid: false,
                bandwith: '22 MHZ',
                upTime: '(721684) 4 days, 08:20:09',
                equipment: 'ACB',
                description: 'modem',
                cmtsId: 'BG-C-7-GOLF',
                firmware: '2.7.2082.87'
            }
        },
        {
            contractNumber: '31452503',
            contractMacAddress: 'A3-43-AE-41-2E-D7',
            contractHgwInfo: {
                wifiEnabled: true,
                hgwStandard: '802.11b',
                ipAddress: '192.178.4.1',
                ssid: '365-Net',
                channel: 4,
                security: 'WPA/WPA2-PSK',
                band: '2,4 GHz',
                hiddenSsid: false,
                bandwith: '18 MHZ',
                upTime: '(108268) 7 days, 15:17:01',
                equipment: 'ACB',
                description: 'modem',
                cmtsId: 'BG-C-1-365',
                firmware: '2.2.1004.84'
            }
        },
        {
            contractNumber: '79238775',
            contractMacAddress: 'B6-06-F6-C7-D5-04',
            contractHgwInfo: {
                wifiEnabled: true,
                hgwStandard: '802.11c',
                ipAddress: '192.165.7.1',
                ssid: 'HomeNet',
                channel: 7,
                security: 'WPA/WPA2-PSK',
                band: '2,4 GHz',
                hiddenSsid: false,
                bandwith: '14 MHZ',
                upTime: '(351387) 12 days, 11:17:01',
                equipment: 'ACB',
                description: 'modem',
                cmtsId: 'BG-C-1-HOMENET',
                firmware: '2.2.1004.84'
            }
        },
        {
            contractNumber: '39531833',
            contractMacAddress: '9D-01-4A-A4-CB-91',
            contractHgwInfo: {
                wifiEnabled: true,
                hgwStandard: '802.11n',
                ipAddress: '192.168.1.2',
                ssid: 'XYZ Agency',
                channel: 7,
                security: 'WPA/WPA2-PSK',
                band: '2,4 GHz',
                hiddenSsid: false,
                bandwith: '18 MHZ',
                upTime: '(51313) 7 days, 10:15:17',
                equipment: 'ACB',
                description: 'modem',
                cmtsId: 'BG-C-1-XYZ',
                firmware: '2.2.1004.84'
            }
        },
        {
            contractNumber: '33992438',
            contractMacAddress: 'D7-C4-71-4A-47-35',
            contractHgwInfo: {
                wifiEnabled: true,
                hgwStandard: '802.11n',
                ipAddress: '192.168.1.1',
                ssid: 'SharedNet',
                channel: 7,
                security: 'WPA/WPA2-PSK',
                band: '2,4 GHz',
                hiddenSsid: false,
                bandwith: '15 MHZ',
                upTime: '(13515) 14 days, 21:18:05',
                equipment: 'ACB',
                description: 'modem',
                cmtsId: 'BG-C-1-SNET',
                firmware: '4.1.1004.0'
            }             
        },
        { 
            contractNumber: '93603004', 
            contractMacAddress: '0D-D3-6B-05-86-59',
            contractHgwInfo: {
                wifiEnabled: true,
                hgwStandard: '802.11n',
                ipAddress: '192.168.1.7',
                ssid: 'SupremeWifi',
                channel: 7,
                security: 'WPA/WPA2-PSK',
                band: '2,4 GHz',
                hiddenSsid: false,
                bandwith: '20 MHZ',
                upTime: '(1483) 3 days, 18:45:17',
                equipment: 'ACB',
                description: 'modem',
                cmtsId: 'BG-C-1-SUPREME',
                firmware: '4.1.1004.0'
            }              
        }
    ]
    //each contract Table data
    // tableRepresentationOfContracts: [
    //     {// contractNumber:'54867972'
    //         hgwInfo: {
    //             contractNumber: '54867972',
    //             wifiEnabled: true,
    //             hgwStandard: '802.11b',
    //             ipAddress: '192.168.1.1',
    //             macAddress: '58-90-77-22-75-5C',
    //             ssid: 'ibis-wifi',
    //             channel: 6,
    //             security: 'WPA/WPA2-PSK',
    //             band: '2,4 GHz',
    //             hiddenSsid: false,
    //             bandwith: '22 MHZ',
    //             upTime: '(34572) 2 days, 19:04:10',
    //             equipment: 'ACB',
    //             description: 'modem',
    //             cmtsId: 'BG-C-1-IBIS',
    //             firmware: '2.2.1004.78'
    //         },
    //         overallStatus: dataLevels.statusMedium,
    //         rssStatus: dataLevels.statusBad,
    //         clientRssStatus: dataLevels.statusMedium,
    //         stickyClientStatus: dataLevels.statusGood,
    //         interferenceStatus: { overall: dataLevels.statusMedium, coChanel: dataLevels.statusGood, adjacent: dataLevels.statusBad },
    //         hgwInterference: { unifi: dataLevels.statusGood, home: dataLevels.statusMedium },
    //         retransmission: { status: dataLevels.statusBad, hgwNumber: 5515 },
    //         numberOfClients: { total: 120, maxNumber: 10 },
    //         hgwCombinedStatus: { clients: 15, stickyClients: 2, dataTransfered: 5.7 },
    //         hgwBigrate: { min: 15, avg: 15, max: 15, last: 15 },
    //         hgwTotalTraffic: 5.7,
    //         hgwRss: { min: -40, avg: -35, max: -30, last: -32 },
    //         hgwInterferenceNetworkRss: { avg: -42, max: -35, last: -40 },
    //         pieWifiConnectedTime: 48,
    //         pieHgwWifiUsage: { low: 20, medium: 35, high: 45 },
    //         pieHgwInterference: { low: 46, medium: 28, high: 26 },
    //         pieHgwInterferenceHome: { low: 3, medium: 77, high: 20 },
    //         pieHgwChannel: { autoChannelEnabled: true, currentChannel: 18, channelChangesNumber: 83, autoYes: 48, autoNo: 52 },
    //         hgwStickyClientsTime: 48,
    //         pieHgwClientsRssStatus: { good: 46, medium: 28, bad: 26 },
    //         pieHgwRssStatus: { good: 7, medium: 88, bad: 5 }
    //     },
    //     {// contractNumber:'31495080'
    //         hgwInfo: {
    //             contractNumber: '31495080',
    //             wifiEnabled: false,
    //             hgwStandard: '802.11b',
    //             ipAddress: '192.168.1.1',
    //             macAddress: '5A-3D-30-13-8F-15',
    //             ssid: 'golf-net',
    //             channel: 12,
    //             security: 'WPA/WPA2-PSK',
    //             band: '2,4 GHz',
    //             hiddenSsid: false,
    //             bandwith: '22 MHZ',
    //             upTime: '(721684) 4 days, 08:20:09',
    //             equipment: 'ACB',
    //             description: 'modem',
    //             cmtsId: 'BG-C-7-GOLF',
    //             firmware: '2.7.2082.87'
    //         },
    //         overallStatus: dataLevels.statusBad,
    //         rssStatus: dataLevels.statusBad,
    //         clientRssStatus: dataLevels.statusMedium,
    //         stickyClientStatus: dataLevels.statusBad,
    //         interferenceStatus: { overall: dataLevels.statusGood, coChanel: dataLevels.statusGood, adjacent: dataLevels.statusMedium },
    //         hgwInterference: { unifi: dataLevels.statusMedium, home: dataLevels.statusMedium },
    //         retransmission: { status: dataLevels.statusMedium, hgwNumber: 7722 },
    //         numberOfClients: { total: 37, maxNumber: 5 },
    //         hgwCombinedStatus: { clients: 14, stickyClients: 7, dataTransfered: 20.3 },
    //         hgwBigrate: { min: 9, avg: 27, max: 120, last: 40 },
    //         hgwTotalTraffic: 10.7,
    //         hgwRss: { min: -17, avg: -25, max: -43, last: -37 },
    //         hgwInterferenceNetworkRss: { avg: -52, max: -70, last: -15 },
    //         pieWifiConnectedTime: 15,
    //         pieHgwWifiUsage: { low: 15, medium: 35, high: 50 },
    //         pieHgwInterference: { low: 28, medium: 60, high: 12 },
    //         pieHgwInterferenceHome: { low: 17, medium: 6, high: 77 },
    //         pieHgwChannel: { autoChannelEnabled: true, currentChannel: 4, channelChangesNumber: 18, autoYes: 77, autoNo: 43 },
    //         hgwStickyClientsTime: 38,
    //         pieHgwClientsRssStatus: { good: 80, medium: 9, bad: 11 },
    //         pieHgwRssStatus: { good: 50, medium: 34, bad: 16 }
    //     },
    //     {// contractNumber:'31452503'
    //         hgwInfo: {
    //             contractNumber: '31452503',
    //             wifiEnabled: true,
    //             hgwStandard: '802.11b',
    //             ipAddress: '192.178.4.1',
    //             macAddress: 'A3-43-AE-41-2E-D7',
    //             ssid: '365-Net',
    //             channel: 4,
    //             security: 'WPA/WPA2-PSK',
    //             band: '2,4 GHz',
    //             hiddenSsid: false,
    //             bandwith: '18 MHZ',
    //             upTime: '(108268) 7 days, 15:17:01',
    //             equipment: 'ACB',
    //             description: 'modem',
    //             cmtsId: 'BG-C-1-365',
    //             firmware: '2.2.1004.84'
    //         },
    //         overallStatus: dataLevels.statusGood,
    //         rssStatus: dataLevels.statusMedium,
    //         clientRssStatus: dataLevels.statusMedium,
    //         stickyClientStatus: dataLevels.statusGood,
    //         interferenceStatus: { overall: dataLevels.statusMedium, coChanel: dataLevels.statusMedium, adjacent: dataLevels.statusMedium },
    //         hgwInterference: { unifi: dataLevels.statusMedium, home: dataLevels.statusMedium },
    //         retransmission: { status: dataLevels.statusMedium, hgwNumber: 13548 },
    //         numberOfClients: { total: 44, maxNumber: 7 },
    //         hgwCombinedStatus: { clients: 60, stickyClients: 15, dataTransfered: 250.5 },
    //         hgwBigrate: { min: 18, avg: 23, max: 30, last: 25 },
    //         hgwTotalTraffic: 20.05,
    //         hgwRss: { min: -10, avg: -14, max: -17, last: -10 },
    //         hgwInterferenceNetworkRss: { avg: -37, max: -57, last: -43 },
    //         pieWifiConnectedTime: 95,
    //         pieHgwWifiUsage: { low: 5, medium: 17, high: 78 },
    //         pieHgwInterference: { low: 10, medium: 14, high: 76 },
    //         pieHgwInterferenceHome: { low: 5, medium: 27, high: 68 },
    //         pieHgwChannel: { autoChannelEnabled: true, currentChannel: 13, channelChangesNumber: 15, autoYes: 78, autoNo: 22 },
    //         hgwStickyClientsTime: 14,
    //         pieHgwClientsRssStatus: { good: 18, medium: 14, bad: 68 },
    //         pieHgwRssStatus: { good: 15, medium: 80, bad: 5 }
    //     },
    //     {// contractNumber:'79238775' 
    //         hgwInfo: {
    //             contractNumber: '79238775',
    //             wifiEnabled: true,
    //             hgwStandard: '802.11c',
    //             ipAddress: '192.165.7.1',
    //             macAddress: 'B6-06-F6-C7-D5-04',
    //             ssid: 'HomeNet',
    //             channel: 7,
    //             security: 'WPA/WPA2-PSK',
    //             band: '2,4 GHz',
    //             hiddenSsid: false,
    //             bandwith: '14 MHZ',
    //             upTime: '(351387) 12 days, 11:17:01',
    //             equipment: 'ACB',
    //             description: 'modem',
    //             cmtsId: 'BG-C-1-HOMENET',
    //             firmware: '2.2.1004.84'
    //         },
    //         overallStatus: dataLevels.statusBad,
    //         rssStatus: dataLevels.statusBad,
    //         clientRssStatus: dataLevels.statusMedium,
    //         stickyClientStatus: dataLevels.statusBad,
    //         interferenceStatus: { overall: dataLevels.statusBad, coChanel: dataLevels.statusMedium, adjacent: dataLevels.statusBad },
    //         hgwInterference: { unifi: dataLevels.statusBad, home: dataLevels.statusMedium },
    //         retransmission: { status: dataLevels.statusBad, hgwNumber: 153 },
    //         numberOfClients: { total: 215, maxNumber: 30 },
    //         hgwCombinedStatus: { clients: 180, stickyClients: 77, dataTransfered: 450.10 },
    //         hgwBigrate: { min: 40, avg: 70, max: 120, last: 87 },
    //         hgwTotalTraffic: 74.35,
    //         hgwRss: { min: -80, avg: -90, max: -170, last: -101 },
    //         hgwInterferenceNetworkRss: { avg: -58, max: -64, last: -61 },
    //         pieWifiConnectedTime: 40,
    //         pieHgwWifiUsage: { low: 70, medium: 22, high: 8 },
    //         pieHgwInterference: { low: 68, medium: 28, high: 4 },
    //         pieHgwInterferenceHome: { low: 84, medium: 9, high: 7 },
    //         pieHgwChannel: { autoChannelEnabled: true, currentChannel: 7, channelChangesNumber: 30, autoYes: 15, autoNo: 75 },
    //         hgwStickyClientsTime: 54,
    //         pieHgwClientsRssStatus: { good: 4, medium: 17, bad: 79 },
    //         pieHgwRssStatus: { good: 7, medium: 20, bad: 73 }
    //     }
    // ],
    // graphsRepresentationOfContracts: [
    //     {// contractNumber:'79238775' 
    //         contractNumber: '79238775',
    //         chartData: [
    //             { date: '2012-07-28', value: 11 },
    //             { date: '2012-07-29', value: 15 },
    //         ]         
    //     }
    // ]
}